### PR TITLE
changing how we check for edit/add

### PR DESCRIPTION
**Pull request by Broham**
was throwing an error on edit before

### CODE REVIEW

**Comment by jgoley** [comment]
We might also want to remove the `add` or `edit` properties we pass to the templates? Like here:
https://github.com/ecohealthalliance/eidr-connect/blob/master/client/controllers/incidentReports/newIncidentFromSelection.coffee#L76

**Comment by nathanathan** [comment]
I see a place where the edit variable is still being used in suggestedIncidentModal.coffee

**Comment by nathanathan** [comment]
Is this PR for this story? https://www.pivotaltracker.com/story/show/145281545

**Comment by Broham** [comment]
@nathanathan - yes it's for that story

**Comment by nathanathan** [comment]
I'm still seeing errors when editing incidents on the /extract-incidents page.

**Comment by Broham** [comment]
@nathanathan - weird, what steps are you taking to get the error.  This is how I was testing:
 1. Go to http://localhost:3000/extract-incidents
 2. Either paste in text or click on the "From the Web" tab and paste in URL
 3. Click "Extract Incidents" 
 4. Click on one of the suggested incidents, edit and click the "Save and Accept" button

**Comment by nathanathan** [comment]
I tried pasting in text when I tested it.

**Comment by Broham** [comment]
@nathanathan - yeah i've tested with both and they both seem to work.  If you test with the same article that I did do you get the error?

**Comment by Broham** [comment]
@jgoley - are you getting any errors?

**Comment by nathanathan** [comment]
I tried this url (http://www.promedmail.org/post/2579682) and got a server error:
```
I20170518-13:38:07.438(-4)? Exception while invoking method 'editIncidentReport' TypeError: Cannot read property '_id' of null
I20170518-13:38:07.439(-4)?     at [object Object].Meteor.methods.editIncidentReport (methods/incidentReports.coffee:41:35)
I20170518-13:38:07.440(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20170518-13:38:07.440(-4)?     at packages/ddp-server/livedata_server.js:711:19
I20170518-13:38:07.440(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170518-13:38:07.441(-4)?     at packages/ddp-server/livedata_server.js:709:40
I20170518-13:38:07.441(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170518-13:38:07.441(-4)?     at packages/ddp-server/livedata_server.js:707:46
I20170518-13:38:07.442(-4)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20170518-13:38:07.442(-4)?     at packages/ddp-server/livedata_server.js:551:43
```
Maybe adding a test would help track down the issue.

**Comment by jgoley** [comment]
I tried http://www.promedmail.org/post/2579682 and http://www.promedmail.org/post/5042859 (both link and raw text) No server errors for me.

**Comment by jgoley** [comment]
Should we also apply the changes to the incidentModal? Here: https://github.com/ecohealthalliance/eidr-connect/blob/master/client/controllers/incidentReports/incidentModal.coffee#L62

**Comment by nathanathan** [comment]
@jgoley Yes

**Comment by nathanathan** [comment]
👍 Looks good

**Pull request merged**
