### PR TITLE
Event page update styles of event details

### PR DESCRIPTION
**Pull request by jgoley**
This reworks the event-info details UI (counts, createdAt, modifiedAt, etc) to match the mockups
It also changes how the copied confirmation is presented to the user — the state of the button changes momentarily. (abandons the toast confirmation)

### CODE REVIEW

**Comment by nathanathan** [comment]
I like the copy button animation. The formatting on the event metadata is doesn't break across lines well:
screen shot 2016-11-02 at 10 34 41 pm

**Comment by jgoley** [comment]
Ohh, that's not cool. I'll fix that and go ahead and style things for smaller screens.

**Comment by jgoley** [comment]
@nathanathan de610e0 should take care of the text flow issues and improve the responsiveness of the metadata area.

**Comment by nathanathan** [comment]
👍 Looks good

**Pull request merged**
