### PR TITLE
Add choropleth layer to affected areas map

### PR DESCRIPTION
**Pull request by nathanathan**
Story: https://www.pivotaltracker.com/story/show/148836615

### CODE REVIEW

**Comment by jgoley** [comment]
I'm not seeing the choropleth or marker layers.
Looks like `/world.geo.json` is required?

**Comment by nathanathan** [comment]
@jgoley Sorry, I forgot to add the geo.json file. The marker layers aren't implemented this this PR.

**Comment by jgoley** [comment]
Question: when the template loads, the geo.json file downloads. What happens if the user interacts with the map before it's finished?

Looks good! 👍

**Comment by jgoley** [comment]
Also: We should probably zoom the map out to contain all the highlighted countries if the view does not initially contain them?

**Comment by nathanathan** [comment]
@jgoley If the user interacts with the map before the geojson loads the choropleth layer will load when it's finished and their viewport will be preserved.

Zooming the map around when the layers change might not be what users want.

**Pull request merged**
