### PR TITLE
Inline form validation

### PR DESCRIPTION
**Pull request by jgoley**
~~*Need to fix all the broken tests~~
Some of the forms required a little finagling since we often listen for click events of buttons outside of the form instead the form's submission event. 

[PT Story](https://www.pivotaltracker.com/story/show/134791781)

### CODE REVIEW

**Comment by nathanathan** [comment]
Saving edits on the event sources form isn't working.

**Comment by nathanathan** [comment]
On the incident form the cumulative checkbox isn't being saved when checked. Also, when editing an incident, the location field will be shown as invalid unless it is modified.

**Comment by jgoley** [comment]
@nathanathan I've fixed the bugs related to editing sources and incident reports.
There seems to be an issue with the validation when a location is not selected and the field is focused. The `has-error` class is not applied until the input looses focus. I'm not sure what is causing it but will look into it.

**Comment by nathanathan** [comment]
👍

**Pull request merged**
