### PR TITLE
rolling back revision changes

### PR DESCRIPTION
**Pull request by Broham**
These are no longer needed

### CODE REVIEW

**Comment by nathanathan** [comment]
I don't think there is a reason to get rid of this. It could be useful for debugging.

**Comment by Broham** [comment]
@nathanathan - what do you think we would use it for for debugging?

**Comment by nathanathan** [comment]
We could use it to verify the correct version of the app is deployed.

**Comment by Broham** [comment]
Ok - lets leave it then.  I'll make sure the `requirements.txt` file is being created correctly.

**Pull request closed without merging**
