### PR TITLE
Improve UX of source addition and IR review

### PR DESCRIPTION
**Pull request by jgoley**
Establishes an improved UX for source addition and IR review. Animates modals off and on stage and adds notifications informing the user the results of their actions.

Also:
- Makes the snippet equal (and scrollable) to the height of the form if it is greater.
- Updates to position of the loading indicator in the suggested sources list
- fixes [this bug](https://www.pivotaltracker.com/story/show/138184901)

### CODE REVIEW

**Comment by nathanathan** [comment]
👍 Looks great!

**Comment by nathanathan** [comment]
@jgoley Some of the tests are failing. They may need to be updated due to the UI changes. Could you investigate the cause of the failures?

**Comment by jgoley** [comment]
@nathanathan I thought about this after submitting the PR. I'll take a look today.

**Comment by jgoley** [comment]
@nathanathan I've fixed the failing tests. Let me know if you see any other issues.

**Pull request merged**
