### PR TITLE
adding soft delete logic

### PR DESCRIPTION
**Pull request by Broham**
Marking userEvent records as deleted instead of actually deleting them.

### CODE REVIEW

**Comment by nathanathan** [comment]
The query in the server router also needs to be updated.

**Comment by Broham** [comment]
@nathanathan - ok, added

**Comment by nathanathan** [comment]
I noticed a couple other issues. The deleted events are still showing up in the suggested events list on the curator inbox. Also, the event pages for the deleted events are still accessible. I think they should only display a message like "This event has been deleted."

**Comment by nathanathan** [comment]
👍 Looks good

**Pull request merged**
