### PR TITLE
Adding title to doc when adding source.  

### PR DESCRIPTION
**Pull request by Broham**
If a title is available for the document we will now display it.  Will have a separate job that will update documents to include the title.

### CODE REVIEW

**Comment by nathanathan** [comment]
This should also provide a way to set the title for articles that are added by url rather than from the suggestions, save the title of articles added through the curator inbox, and update the article schema.

**Comment by Broham** [comment]
ok @nathanathan I pushed an update that includes a startup script to set the promed titles.  Take a look and let me know if this is what you had in mind.

**Comment by nathanathan** [comment]
@Broham The update looks great. That is what I had in mind.

**Comment by Broham** [comment]
@nathanathan is there anything else I need to do on this guy?

**Comment by nathanathan** [comment]
@Broham Yes, you should also provide a way for users to set the title for articles that are added by url and set the title of articles added through the curator inbox.

**Comment by Broham** [comment]
This should be good to go now @nathanathan

**Comment by nathanathan** [comment]
The title field on the article form is not being saved.

**Comment by Broham** [comment]
@nathanathan fixed

**Comment by nathanathan** [comment]
👍 Looks good

**Pull request merged**
